In [1]:
import re
import json
import spacy

In [2]:
#STOP WORDS
stop_words = ['in','intersect','except','union','not']
def get_queries(query):
    queries=[]
    runing_query=[]
    i = 1
    runing_query.append(query[0])
    while i < len(query):
        token = query[i]
        if token == '.':
            runing_query.pop()
            i+=1
            continue
        if token == 'as':
            i+=2
            continue 
        if token == 'by' or token == ',' or token == 'distinct': 
            i+=1
            continue
        if token == 'select':
            prev_token = query[i-1]
            nested_query = []
            if prev_token == '(':
                #WHILE TO GET BRACKET END
                open_bracket = 1
                while open_bracket >=1:
                    token = query[i]
                    i+=1
                    if token == '(': open_bracket += 1
                    elif token == ')': open_bracket -= 1
                    if open_bracket == 0: break
                    nested_query.append(token)
            else:
                nested_query = query[i:]
                i = len(query)+1
            nested_queries = get_queries(nested_query)
            queries.extend(nested_queries)
        if token not in stop_words and i <= len(query): runing_query.append(token)
        i+=1
    queries.append(runing_query)
    return queries

In [3]:
bigram_dict = {
    'entity_attributes_select':{},
    'entity_attributes_where':{},
    'entity_attributes_group':{},
    'entity_attributes_having':{},
    'entity_attributes_order':{},
}
trigram_dict = {
    'entity_attributes_select':{},
    'entity_attributes_where':{},
    'entity_attributes_group':{},
    'entity_attributes_having':{},
    'entity_attributes_order':{},
}
dictionaries = {
    'select_attributes':{},
    'entities':{},
    'where_attributes':{},
    'having_attributes':{},
    'group_attributes':{},
    'order_attributes':{}
}
aggregate_attributes = {'max':{},'min':{},'avg':{},'sum':{},'count':{}}
dataSet = []

In [4]:
#Aggregate relations with in select clause
#return arr without max,min,avg,sum,count
def select_aggregate(select_tokens):
    select_attributes = []
    i = 0
    while i < len(select_tokens):
        token = select_tokens[i]
        if token in aggregate_attributes.keys():
            attribute = select_tokens[i+2]
            if aggregate_attributes[token].get(attribute) is None:
                aggregate_attributes[token][attribute] = 0
            aggregate_attributes[token][attribute] += 1
            select_attributes.append(attribute)
            i+=3
        else:
            select_attributes.append(token)
        i+=1

    return select_attributes

In [5]:
#Operations in where clause
#<=,<,>,>=,=,!=,like,not 
#like,in,not in,between,not between
#---------------------------------
#and,or,not
op = ['<=','<','>=','>','=','!=','like','not','in','not in','between','not between','and','or','not','value']
def where_attributes(where_tokens):
    where_attributes = []
    for token in where_tokens:
        if token not in op: where_attributes.append(token)
    return where_attributes

In [6]:
#Language Model
def generate_bigram(entities,attributes,dict_type):
    for entity in entities:
        for attribute in attributes:
            bigram = entity + ' ' + attribute
            if bigram_dict[dict_type].get(bigram) is None:
                bigram_dict[dict_type][bigram] = 0
            bigram_dict[dict_type][bigram] += 1

#Language Model
def generate_trigram(entities,attributes,dict_type):
    entities.sort()
    for i in range(len(entities)):
        for j in range(i+1,len(entities)):
            for attribute in attributes:
                trigram = entities[i] + ' ' + entities[j] + ' ' + attribute
                if trigram_dict[dict_type].get(trigram) is None:
                    trigram_dict[dict_type][trigram] = 0
                trigram_dict[dict_type][trigram] += 1

In [7]:
nlp = spacy.load('en_core_web_sm')

def get_lemma(text):
    doc = nlp(text)
    return doc[0].lemma_

def camel_case_paskal_split(identifier):
    matches = re.finditer('.+?(?:(?<=[a-z])(?=[A-Z])|(?<=[A-Z])(?=[A-Z][a-z])|$)', identifier)
    return [m.group(0) for m in matches]

def cleanName(colName):
    #remove names with one character 
    if len(colName) <= 1: return colName
    #seperate pascal and camel cases
    Names = camel_case_paskal_split(colName)
    clean_Names=[]
    for name in Names:
      #remove names that are only numbers
      result = re.search("^[ 0-9]+$", name)
      if result is not None: continue
      #remove numbers at the end of the string 
      name = re.sub("[0-9]+$", '', name)
      #lower
      name = name.lower()
      lemma = get_lemma(name)
      clean_Names.append(lemma)
      
    return clean_Names
    
def cleanEntityName(entityName):
  entityName = entityName.strip()
  entityName = re.split('_| |-',entityName)
  entity_clean=[]
  for name in entityName:
    clean_name = cleanName(name)
    entity_clean.extend(clean_name)
  return entity_clean

In [10]:
def generate_unigram(query):
    query_dicts = {'select_attributes':[],'entities':[],
    'where_attributes':[],
    'having_attributes':[],
    'group_attributes':[],
    'order_attributes':[],
    "select_attributes_clean":[],
    "where_attributes_clean":[],
    }
    current_dict = 'select_attributes'
    for token in query:
        if token =='select':
            continue

        if token =='from' or token == 'join':
            current_dict = 'entities'
            continue

        if token =='where' or token == 'on':
            current_dict = 'where_attributes'
            continue

        if token =='group':
            current_dict = 'group_attributes'
            continue

        if token == 'having':
            current_dict = 'having_attributes'
            continue

        if token == 'order':
            current_dict = 'order_attributes'
            continue
        
        if token == 'limit': return query_dicts


        if current_dict == 'entities':
            token = cleanEntityName(token)
            for t in token:
                if dictionaries[current_dict].get(t) is None:
                    dictionaries[current_dict][t] = 0
                dictionaries[current_dict][t] += 1
                query_dicts[current_dict].append(t)
            continue

        if dictionaries[current_dict].get(token) is None:
            dictionaries[current_dict][token] = 0

        dictionaries[current_dict][token] += 1
        query_dicts[current_dict].append(token)
    return query_dicts

In [11]:
def get_vocab(dataSet):
    vocab = set()
    for queriy in dataSet:
        for entity in queriy['entities']:
            vocab.add(entity)
    return vocab

In [12]:
queries = []
with open('/home/hager/college/GP/NLP2SQL/Search Engine/train_spider.json', 'r',encoding='UTF-8') as file:
    data = json.load(file)
    for query in data:
        query_tokens = query['query_toks_no_value']
        current_queries = get_queries(query_tokens)      
        queries.extend(current_queries)

In [13]:
for query in queries:
    q_data = generate_unigram(query)
    q_data['select_attributes_clean'] = select_aggregate(q_data['select_attributes'])
    q_data['where_attributes_clean'] = where_attributes(q_data['where_attributes'])
    generate_bigram(q_data['entities'],q_data['select_attributes_clean'],'entity_attributes_select')
    generate_bigram(q_data['entities'],q_data['where_attributes_clean'],'entity_attributes_where')
    '''
    generate_trigram(q_data['entities'],q_data['select_attributes_clean'],'entity_attributes_select')
    generate_trigram(q_data['entities'],q_data['where_attributes_clean'],'entity_attributes_where')
    '''
    dataSet.append(q_data)

In [14]:
print(len(dataSet))
print(dataSet[19])

8062
{'select_attributes': ['count', '(', '*', ')'], 'entities': ['farm'], 'where_attributes': [], 'having_attributes': [], 'group_attributes': [], 'order_attributes': [], 'select_attributes_clean': ['*'], 'where_attributes_clean': []}

In [98]:
vocab = get_vocab(dataSet)
print(len(vocab))
print(vocab)

423
{'unit', 'flight', 'safety', 'service', 'in', 'premise', 'availability', 'physician', 'build', 'stock', 'music', 'head', 'additional', 'wine', 'sale', 'staff', 'aircraft', 'market', 'amenity', 'repair', 'live', 'activity', 'supplier', 'fame', 'mediatype', 'teach', 'claim', 'phone', 'outcome', 'user', 'artwork', 'membership', 'player', 'useracct', 'regular', 'student', 'delivery', 'individual', 'performer', 'circuit', 'band', 'drama', 'tweet', 'characteristic', 'policy', 'customer', 'discount', 'tourist', 'with', 'vote', 'view', 'league', 'actual', 'copy', 'county', 'instrument', 'route', 'injury', 'processing', 'exhibition', 'registration', 'elimination', 'workshop', 'match', 'management', 'camera', 'calendar', 'musical', 'roller', 'mailshot', 'contract', 'course', 'to', 'apartment', 'nomination', 'personfriend', 'invoice', 'chain', 'trip', 'branch', 'first', 'truck', 'client', 'financial', 'grape', 'journalist', 'register', 'round', 'review', 'architect', 'agent', 'builder', 'available', 'tutor', 'schedule', 'station', 'visitor', 'inst', 'church', 'research', 'season', 'guest', 'job', 'host', 'star', 'album', 'behavior', 'film', 'rental', 'submission', 'pilot', 'appointment', 'payment', 'technician', 'card', 'railway', 'image', 'incident', 'line', 'broadcast', 'attribute', 'race', 'department', 'faculty', 'test', 'photo', 'wedding', 'area', 'medicine', 'organisation', 'vocal', 'endowment', 'coach', 'maintenance', 'acceptance', 'volume', 'prescribe', 'employee', 'office', 'airport', 'tryout', 'accelerator', 'home', 'enrollment', 'browser', 'people', 'news', 'feature', 'check', 'song', 'master', 'undergoe', 'building', 'result', 'party', 'farm', 'prereq', 'assignment', 'institution', 'thing', 'functional', 'ship', 'overpayment', 'professor', 'project', 'report', 'marketing', 'booking', 'hire', 'assessment', 'group', 'header', 'cinema', 'genre', 'hall', 'product', 'stage', 'teacher', 'happy', 'address', 'basketball', 'section', 'class', 'manufacte', 'manufacturer', 'expense', 'bridge', 'rank', 'stay', 'account', 'and', 'resident', 'tracklist', 'city', 'chip', 'hotel', 'editor', 'minor', 'bus', 'coupon', 'affiliate', 'third', 'climber', 'paper', 'council', 'list', 'university', 'sportsinfo', 'category', 'fee', 'culture', 'record', 'track', 'entrepreneur', 'subject', 'language', 'status', 'organization', 'playlist', 'asset', 'destroy', 'performance', 'channel', 'mode', 'electoral', 'mail', 'author', 'manager', 'award', 'be', 'discipline', 'mill', 'tax', 'note', 'medication', 'club', 'appellation', 'settlement', 'fix', 'content', 'facility', 'complaint', 'lot', 'weather', 'movie', 'draft', 'employment', 'shipment', 'restaurant', 'attraction', 'enrol', 'college', 'participate', 'authorship', 'video', 'bank', 'team', 'certificate', 'debate', 'advisor', 'family', 'furniture', 'member', 'constructor', 'candidate', 'public', 'vehicle', 'contact', 'assignedto', 'stadium', 'classroom', 'lens', 'reviewer', 'block', 'degree', 'notification', 'swimmer', '(', 'dependent', 'task', 'skill', 'compatible', 'interaction', 'competition', 'type', 'problem', 'wrestler', 'grant', 'purchase', 'csu', 'machine', 'gradeconversion', 'fine', 'mountain', 'require', 'allergy', 'cross', 'model', 'accident', 'gas', ')', 'on', 'parking', 'index', 'part', 'campus', 'device', 'program', 'cmi', 'trust', 'constructorstanding', 'captain', 'take', 'form', 'item', 'rate', 'detention', 'time', 'driverstanding', 'hour', 'dorm', 'procedure', 'body', 'fault', 'call', 'museum', 'detail', 'document', 'festival', 'royal', 'circulation', 'airline', 'order', 'enzyme', 'book', 'screen', 'property', 'benefit', 'nurse', 'street', 'mission', 'participant', 'room', 'business', 'pitstop', 'medium', 'district', 'franchise', 'color', 'profile', 'follow', 'person', 'coaster', 'campaign', 'structure', 'game', 'visit', 'history', 'store', 'publication', 'committee', 'reference', 'artist', 'company', 'rent', 'loss', 'lesson', 'gymnast', 'operate', 'school', 'investor', 'reservation', 'inventory', 'salary', 'postseason', 'region', 'definition', 'dept', 'loan', 'arrear', 'election', 'representative', 'journal', 'log', 'role', 'event', 'catalog', 'instructor', 'of', 'scientist', 'engineer', 'transaction', 'park', 'enrolment', 'shop', 'storm', 'laptime', 'affect', 'estimation', 'ref', 'driver', 'code', 'actor', 'all', 'temperature', 'patient', 'saving', 'have', 'play', 'location', 'rating', 'train', 'budget', 'statement', 'country', 'attendance', 'for', 'web', 'perpetrator', 'file', 'weekly', 'enroll', 'protein'}

In [102]:
import pickle
with open('/home/hager/college/GP/NLP2SQL/Search Engine/dataSet.pickle', 'wb') as handle:
    pickle.dump(dataSet, handle, protocol=pickle.HIGHEST_PROTOCOL)

with open('/home/hager/college/GP/NLP2SQL/Search Engine/vocab.pickle', 'wb') as handle:
    pickle.dump(vocab, handle, protocol=pickle.HIGHEST_PROTOCOL)

In [104]:
with open('/home/hager/college/GP/NLP2SQL/Search Engine/dataSet.pickle', 'rb') as handle:
    dataSetL = pickle.load(handle)
print(len(dataSetL))

10337

In [4]:
testSchema = {
    11: 
    {'TableName': 'DEPARTMENT', 
    'TableType':'',
    'attributes': {'name': 'str', 
    'start_date': 'datetime',
    'EMPLOYEE_Manages': 'str'}, 
    'primaryKey': ['name'], 
    'ForgeinKey': [{'attributeName': 'EMPLOYEE_Manages',
    'ForignKeyTable': 'EMPLOYEE', 
    'ForignKeyTableAttributeName': 'ssn', 
    'patricipaction': 'partial', 
    'dataType': 'str'}], 
    'isWeak': False},
    34: 
    {'TableName': 'DEPARTMENT_Clocation', 
    'TableType':'',
    'attributes': {'Clocation': 'str',
    'DEPARTMENT_name': 'str'}, 
    'primaryKey': ['Clocation', 
    'DEPARTMENT_name'], 
    'ForgeinKey': [{'attributeName': 'DEPARTMENT_name', 
    'ForignKeyTable': 'DEPARTMENT', 
    'ForignKeyTableAttributeName': 'name', 
    'patricipaction': 'full', 
    'dataType': 'str'}], 
    'isWeak': False}, 
    12: 
    {'TableName': 'EMPLOYEE',
    'TableType':'',
    'attributes': {'last_name': 'str', 
    'middle_initis': 'str', 
    'first_name': 'str', 
    'address': 'str',
    'salary': 'float',
    'sex': 'str', 
    'status': 'str', 
    'birth_dat': 'str', 
    'ssn': 'str',
    'start_date': 'datetime',
    'DEPARTMENT_Employed_name': 'str',
    'EMPLOYEE_Supervision_': 'str'},
    'primaryKey': ['ssn'], 
    'ForgeinKey': [{'attributeName': 'DEPARTMENT_Employed_name',
    'ForignKeyTable': 'DEPARTMENT', 'ForignKeyTableAttributeName': 'name',
    'patricipaction': 'full', 'dataType': 'str'}, 
    {'attributeName': 'EMPLOYEE_Supervision_', 
    'ForignKeyTable': 'EMPLOYEE', 
    'ForignKeyTableAttributeName': 'ssn',
    'patricipaction': 'partial', 
    'dataType': 'str'}], 
    'isWeak': False},
    24: {'TableName': 'PROJECT', 
    'TableType':'',
    'attributes': {'location': 'str',
    'name': 'str', 
    'budget': 'float',
    'DEPARTMENT_Assigned_name': 'str'}, 
    'primaryKey': ['name'], 
    'ForgeinKey': [{'attributeName': 'DEPARTMENT_Assigned_name',
    'ForignKeyTable': 'DEPARTMENT', 
    'ForignKeyTableAttributeName': 'name',
    'patricipaction': 'partial', 
    'dataType': 'str'}], 
    'isWeak': False}, 
    25: 
    {'TableName': 'DEPENDENT',
    'TableType':'',
    'attributes': {'sex': 'str', 
    'relatlonship': 'str',
    'name': 'str',
    'birth_date': 'datetime', 
    'Dependents_EMPLOYEE_': 'str'}, 
    'primaryKey': ['Dependents_EMPLOYEE_'], 
    'ForgeinKey': [{'attributeName': 'Dependents_EMPLOYEE_', 
    'ForignKeyTable': 'EMPLOYEE', 
    'ForignKeyTableAttributeName': 'ssn', 
    'patricipaction': 'partial', 
    'dataType': 'str'}], 
    'isWeak': True}, 
    35: 
    {'TableName': 'Works_EMPLOYEE_PROJECT', 
    'TableType':'mTm',
    'attributes': {'start_date': 'datetime', 
    'hours': 'int', 
    'EMPLOYEE_': 'str', 
    'PROJECT_': 'str'}, 
    'primaryKey': ['EMPLOYEE_', 'PROJECT_'], 
    'ForgeinKey': [{'attributeName': 'EMPLOYEE_', 
    'ForignKeyTable': 'EMPLOYEE',
    'ForignKeyTableAttributeName': 'ssn', 
    'patricipaction': 'full',
    'dataType': 'str'}, 
    {'attributeName': 'PROJECT_',
    'ForignKeyTable': 'PROJECT', 
    'ForignKeyTableAttributeName': 'name',
    'patricipaction': 'full',
    'dataType': 'str'}], 
    'isWeak': False}}

import pickle
with open('/home/hager/college/GP/GP/src/SearchEngine/testSchema.pickle', 'wb') as handle:
    pickle.dump(testSchema, handle, protocol=pickle.HIGHEST_PROTOCOL)

In [ ]:
def bestJoins(paths):
    minJoins = float("inf")
    Join = None
    for path in paths:
        joinsCount = path.count(' AND ')
        if joinsCount < minJoins:
            minJoins = joinsCount
            Join = path
    
    filteredJoins = []
    prev_joins = set()
    for path in paths:
        if path.count(' AND ') == minJoins:
            joins =  "".join(sorted(re.split(" AND | = ",path.strip())))
            if joins in prev_joins: continue
            filteredJoins.append(path)
            prev_joins.add(joins)
    return filteredJoins

#TODO:give to this function only a connected component graph
def findPathsBFS(source,goals,graph):
    queue = deque()
    queue.append((source,""))
    paths = set()
    visited = set()
    visited.add(source)
    while queue:
        curEntity,path = queue.popleft()
        curEntityName = curEntity
        for neighbor in graph[curEntityName]:
            neighborJoin = neighbor['ForignKeyTable']+'.'+neighbor['ForignKeyTableAttributeName']
            newPath = ' '+curEntityName +'.'+neighbor["attributeName"]+ ' = ' +neighborJoin
            if path != '': newPath = path+' AND'+ newPath

            print("path:",newPath , "---- matching:",[" "+entity+"." in newPath for entity in goals])
            ''
            if neighbor['ForignKeyTable'] in goals and neighborJoin not in path\
                 and all(" "+entity+"." in newPath for entity in goals):
                    # print(neighbor['ForignKeyTable'] , newPath)
                    paths.add(newPath)
            #print("visited",neighbor['ForignKeyTable'] not in visited,visited,neighbor['ForignKeyTable'])
            if neighbor['ForignKeyTable'] not in visited:
                print(neighbor['ForignKeyTable'])
                visited.add(neighbor['ForignKeyTable'])
                queue.append((neighbor['ForignKeyTable'],newPath))
    #print("visited------------------------")
    #print(visited)
    return paths

In [197]:
trigram_dict['entity_attributes_select']

{'department head creation': 1,
 'department management creation': 1,
 'head management creation': 1,
 'department management name': 2,
 'department management num_employees': 1,
 'head management age': 1,
 'department head born_state': 2,
 'department management born_state': 2,
 'head management born_state': 2,
 'department management department_id': 1,
 'department management *': 1,
 'city farm_competition year': 2,
 'city farm_competition official_name': 4,
 'city farm_competition status': 2,
 'city farm_competition theme': 2,
 'courses student_course_registrations course_name': 5,
 'candidates people first_name': 2,
 'candidates people last_name': 2,
 'courses student_course_registrations student_id': 3,
 'student_course_registrations students student_details': 4,
 'courses student_course_attendance *': 4,
 'candidates people candidate_id': 2,
 'student_course_registrations students student_id': 2,
 'student_course_registrations students *': 4,
 'courses student_course_registrations *': 2,
 'courses students course_name': 2,
 'courses students *': 2,
 'student_course_registrations students course_name': 2,
 'candidate_assessments candidates cell_mobile_number': 2,
 'candidate_assessments people cell_mobile_number': 2,
 'candidates people cell_mobile_number': 2,
 'addresses people_addresses city': 4,
 'addresses students city': 2,
 'people_addresses students city': 2,
 'courses student_course_attendance student_id': 2,
 'station status name': 8,
 'station trip lat': 6,
 'station trip long': 6,
 'station trip city': 2,
 'station status id': 4,
 'trip weather id': 2,
 'station trip id': 4,
 'station trip installation_date': 2,
 'station trip *': 10,
 'station trip name': 4,
 'station trip duration': 4,
 'station station *': 2,
 'trip trip *': 2,
 'book publication title': 2,
 'book publication publication_date': 1,
 'book publication writer': 1,
 'actor musical name': 12,
 'actor musical *': 2,
 'follows user_profiles *': 1,
 'follows user_profiles name': 2,
 'follows user_profiles email': 1,
 'tweets user_profiles name': 4,
 'follows user_profiles f1': 3,
 'tweets user_profiles *': 2,
 'tweets user_profiles partitionid': 1,
 'catalog_structure catalogs catalog_name': 2,
 'catalog_structure catalogs date_of_publication': 2,
 'catalog_contents catalog_contents_additional_attributes catalog_entry_name': 4,
 'catalog_contents catalog_structure catalog_level_name': 2,
 'attribute_definitions catalog_contents_additional_attributes attribute_name': 2,
 'attribute_definitions catalog_contents_additional_attributes attribute_id': 2,
 'aircraft flight name': 6,
 'aircraft flight flno': 2,
 'aircraft flight *': 2,
 'aircraft certificate name': 16,
 'aircraft employee name': 12,
 'certificate employee name': 14,
 'certificate employee salary': 2,
 'has_allergy student *': 2,
 'allergy_type has_allergy *': 4,
 'allergy_type has_allergy allergytype': 4,
 'allergy_type has_allergy allergy': 2,
 'allergy_type student allergy': 2,
 'allergy_type student allergytype': 2,
 'has_allergy student allergy': 2,
 'has_allergy student allergytype': 2,
 'allergy_type has_allergy stuid': 10,
 'has_allergy student fname': 2,
 'has_allergy student city_code': 2,
 'customers invoices first_name': 8,
 'customers invoices last_name': 8,
 'customers invoices *': 4,
 'customers invoices total': 4,
 'genres tracks name': 12,
 'genres tracks *': 4,
 'albums artists title': 4,
 'albums artists *': 2,
 'customers employees *': 2,
 'employees employees first_name': 4,
 'employees employees last_name': 4,
 'customers employees first_name': 2,
 'customers employees last_name': 2,
 'employees employees reports_to': 2,
 'albums tracks title': 4,
 'albums tracks name': 2,
 'genres media_types name': 4,
 'media_types tracks name': 4,
 'playlist_tracks playlists name': 12,
 'playlist_tracks tracks name': 10,
 'playlists tracks name': 10,
 'customers invoice_lines name': 2,
 'customers invoices name': 2,
 'customers tracks name': 2,
 'invoice_lines invoices name': 2,
 'invoice_lines tracks name': 2,
 'invoices tracks name': 2,
 'editor journal name': 4,
 'editor journal theme': 3,
 'editor journal_committee name': 6,
 'editor journal_committee theme': 3,
 'journal journal_committee name': 4,
 'journal journal_committee theme': 4,
 'editor journal age': 1,
 'editor journal_committee age': 1,
 'journal journal_committee age': 1,
 'editor journal_committee editor_id': 1,
 'editor journal_committee *': 1,
 'journal journal_committee date': 1,
 'journal journal_committee sales': 2,
 'accounts customers customer_first_name': 18,
 'accounts customers customer_last_name': 16,
 'accounts customers customer_phone': 2,
 'accounts customers *': 4,
 'accounts customers customer_id': 8,
 'customers customers_cards customer_first_name': 8,
 'customers customers_cards customer_last_name': 6,
 'customers customers_cards customer_phone': 2,
 'customers customers_cards *': 4,
 'customers customers_cards customer_id': 6,
 'customers_cards financial_transactions card_type_code': 2,
 'customers_cards financial_transactions *': 2,
 'race track name': 12,
 'race track *': 2,
 'race track date': 2,
 'race track location': 2,
 'happy_hour shop address': 1,
 'happy_hour shop shop_id': 1,
 'album artist title': 2,
 'album artist *': 2,
 'album artist name': 8,
 'album track title': 8,
 'album track albumid': 4,
 'album track *': 2,
 'genre track name': 2,
 'mediatype track name': 2,
 'genre track *': 2,
 'genre track unitprice': 4,
 'customer employee firstname': 4,
 'customer employee lastname': 4,
 'customer employee city': 2,
 'customer invoice invoicedate': 2,
 'customer invoice lastname': 2,
 'customer invoice firstname': 2,
 'customer invoice address': 2,
 'mediatype track *': 2,
 'genre track milliseconds': 6,
 'customer employee supportrepid': 2,
 'album artist artistid': 2,
 'album genre title': 4,
 'genre track title': 4,
 'first_notification_of_loss services service_name': 2,
 'claims settlements effective_date': 2,
 'customers customers_policies *': 2,
 'customers customers_policies customer_name': 4,
 'available_policies customers policy_type_code': 4,
 'available_policies customers_policies policy_type_code': 4,
 'customers customers_policies policy_type_code': 4,
 'customers first_notification_of_loss customer_name': 8,
 'customers services customer_name': 6,
 'first_notification_of_loss services customer_name': 6,
 'customers customers_policies date_opened': 2,
 'customers customers_policies date_closed': 2,
 'enzyme medicine name': 4,
 'enzyme medicine_enzyme_interaction name': 8,
 'medicine medicine_enzyme_interaction name': 12,
 'medicine medicine_enzyme_interaction id': 6,
 'medicine medicine_enzyme_interaction fda_approved': 2,
 'enzyme medicine_enzyme_interaction id': 2,
 'enzyme medicine interaction_type': 2,
 'enzyme medicine_enzyme_interaction interaction_type': 2,
 'medicine medicine_enzyme_interaction interaction_type': 2,
 'medicine medicine_enzyme_interaction trade_name': 8,
 'enzyme medicine_enzyme_interaction location': 2,
 'enzyme medicine_enzyme_interaction product': 2,
 'enzyme medicine trade_name': 2,
 'enzyme medicine_enzyme_interaction trade_name': 2,
 'basketball_match university primary_conference': 2,
 'basketball_match university team_name': 4,
 'basketball_match university acc_regular_season': 2,
 'basketball_match university all_games': 2,
 'basketball_match university location': 2,
 'chip_model phone ram_mib': 2,
 'chip_model phone rom_mib': 1,
 'chip_model phone hardware_model_name': 3,
 'chip_model phone company_name': 1,
 'phone screen_mode char_cells': 1,
 'phone screen_mode pixels': 3,
 'phone screen_mode hardware_colours': 1,
 'phone screen_mode hardware_model_name': 5,
 'phone screen_mode company_name': 2,
 'chip_model phone wifi': 1,
 'chip_model phone type': 1,
 'chip_model screen_mode wifi': 1,
 'chip_model screen_mode type': 1,
 'phone screen_mode wifi': 1,
 'phone screen_mode type': 1,
 'chip_model screen_mode hardware_model_name': 1,
 'country match_season season': 2,
 'country match_season player': 4,
 'country match_season country_name': 8,
 'country match_season position': 2,
 'country match_season official_native_language': 4,
 'match_season team season': 2,
 'match_season team player': 2,
 'match_season team name': 2,
 'match_season team position': 2,
 'match_season team college': 2,
 'player team player': 2,
 'player team years_played': 2,
 'country match_season *': 2,
 'climber mountain name': 8,
 'climber mountain height': 4,
 'climber mountain time': 2,
 'body_builder people name': 5,
 'body_builder people birth_date': 1,
 'body_builder people birth_place': 2,
 'body_builder people height': 1,
 'body_builder people total': 2,
 'body_builder people weight': 1,
 'election representative name': 3,
 'election representative date': 1,
 'election representative party': 1,
 'election representative lifespan': 1,
 'election representative votes': 1,
 'apartment_bookings apartments apt_number': 8,
 'apartment_bookings apartments booking_start_date': 12,
 'apartment_bookings apartments booking_status_code': 2,
 'apartment_bookings apartments room_count': 2,
 'apartment_bookings guests guest_first_name': 4,
 'apartment_bookings guests booking_start_date': 8,
 'apartment_bookings guests guest_last_name': 2,
 'apartment_facilities apartments facility_code': 2,
 'apartment_facilities apartments room_count': 2,
 'apartment_buildings apartments room_count': 2,
 'apartment_buildings apartments building_address': 2,
 'apartment_buildings apartments apt_type_code': 2,
 'apartment_buildings apartments apt_number': 2,
 'apartments view_unit_status apt_number': 4,
 'game injury_accident season': 2,
 'game injury_accident id': 3,
 'game injury_accident score': 1,
 'game injury_accident date': 2,
 'game injury_accident name': 6,
 'game stadium id': 3,
 'game stadium name': 6,
 'injury_accident stadium id': 2,
 'injury_accident stadium name': 6,
 'game stadium season': 1,
 'injury_accident stadium season': 1,
 'game injury_accident injury': 1,
 'game injury_accident average_attendance': 1,
 'game injury_accident total_attendance': 1,
 'game stadium average_attendance': 1,
 'game stadium total_attendance': 1,
 'injury_accident stadium average_attendance': 1,
 'injury_accident stadium total_attendance': 1,
 'game stadium *': 1,
 'game injury_accident player': 1,
 'country league name': 2,
 'country league *': 1,
 'player player_attributes player_name': 6,
 'player player_attributes birthday': 1,
 'member member_attendance name': 3,
 'member member_attendance location': 2,
 'member performance name': 3,
 'member performance location': 2,
 'member_attendance performance name': 3,
 'member_attendance performance location': 2,
 'member member_attendance date': 2,
 'member performance date': 2,
 'member_attendance performance date': 2,
 'course prereq title': 4,
 'course prereq credits': 2,
 'course prereq dept_name': 2,
 'student takes name': 6,
 'course instructor title': 2,
 'course instructor name': 4,
 'course teaches title': 2,
 'course teaches name': 4,
 'instructor teaches title': 2,
 'instructor teaches name': 8,
 'advisor instructor name': 10,
 'advisor student name': 10,
 'advisor student i_id': 2,
 'advisor instructor salary': 4,
 'advisor student salary': 4,
 'instructor student name': 8,
 'instructor student salary': 4,
 'course prereq prereq_id': 6,
 'course prereq course_id': 2,
 'course section title': 4,
 'department instructor salary': 2,
 'department instructor *': 2,
 'classroom course title': 2,
 'classroom course credits': 2,
 'classroom section title': 2,
 'classroom section credits': 2,
 'course section credits': 2,
 'course takes id': 2,
 'department instructor id': 4,
 'department instructor dept_name': 2,
 'department student id': 4,
 'department student dept_name': 10,
 'instructor student id': 4,
 'instructor student dept_name': 2,
 'course student name': 2,
 'course takes name': 2,
 'course section building': 2,
 'course section room_number': 2,
 'course section semester': 2,
 'course section year': 2,
 'instructor teaches course_id': 4,
 'debate debate_people name': 3,
 'debate debate_people date': 2,
 'debate debate_people venue': 2,
 'debate people name': 3,
 'debate people date': 2,
 'debate people venue': 2,
 'debate_people people name': 5,
 'debate_people people date': 2,
 'debate_people people venue': 2,
 'debate_people people *': 1,
 'customers policies policy_type_code': 2,
 'claim_headers claims_documents amount_claimed': 2,
 'claim_headers customers customer_details': 4,
 'claim_headers policies customer_details': 4,
 'customers policies customer_details': 14,
 'claims_processing claims_processing_stages claim_status_name': 2,
 'accounts customers account_id': 2,
 'accounts customers date_account_opened': 2,
 'accounts customers account_name': 4,
 'accounts customers other_account_details': 4,
 'accounts customers phone_number': 2,
 'accounts financial_transactions *': 4,
 'accounts financial_transactions account_name': 4,
 'accounts financial_transactions account_id': 4,
 'financial_transactions invoices invoice_number': 2,
 'financial_transactions invoices invoice_date': 2,
 'invoices orders invoice_date': 2,
 'invoices orders order_id': 4,
 'invoices orders order_details': 4,
 'customers orders customer_last_name': 2,
 'customers orders customer_id': 8,
 'customers orders phone_number': 2,
 'order_items products product_name': 11,
 'order_items products product_quantity': 2,
 'order_items orders product_name': 4,
 'order_items orders *': 6,
 'order_items products *': 6,
 'orders products product_name': 4,
 'orders products *': 6,
 'people people name': 3,
 'people wedding name': 7,
 'church wedding name': 3,
 'church people name': 2,
 'artist exhibition name': 10,
 'artist exhibition *': 2,
 'artist exhibition country': 2,
 'artist exhibition theme': 2,
 'exhibition exhibition_record theme': 6,
 'exhibition exhibition_record date': 2,
 'exhibition exhibition_record attendance': 2,
 'exhibition exhibition_record *': 2,
 'artist exhibition_record name': 2,
 'exhibition exhibition_record name': 2,
 'item review title': 10,
 'review useracct name': 4,
 'item review i_id': 2,
 'review useracct rating': 1,
 'review useracct *': 1,
 'trust useracct name': 3,
 'trust useracct trust': 1,
 'coach player player_name': 4,
 'coach player coach_name': 2,
 'coach player_coach player_name': 4,
 'coach player_coach coach_name': 2,
 'player player_coach player_name': 4,
 'player player_coach coach_name': 2,
 'coach player gender': 1,
 'coach player_coach gender': 1,
 'player player_coach gender': 1,
 'club coach club_id': 1,
 'club coach club_name': 1,
 'club coach *': 1,
 'coach match_result club_id': 1,
 'coach match_result gold': 1,
 'gymnast people name': 6,
 'gymnast people total_points': 2,
 'gymnast people age': 4,
 'gymnast people hometown': 10,
 'gymnast people *': 2,
 'accounts savings balance': 32,
 'accounts checking custid': 2,
 'accounts checking name': 24,
 'accounts checking balance': 30,
 'checking savings balance': 30,
 'accounts savings name': 24,
 'checking savings name': 16,
 'accounts checking +': 4,
 'accounts savings +': 4,
 'checking savings +': 6,
 'accounts checking *': 2,
 'accelerator_compatible_browser browser name': 8,
 'accelerator_compatible_browser web_client_accelerator name': 8,
 'browser web_client_accelerator name': 7,
 'accelerator_compatible_browser web_client_accelerator id': 1,
 'accelerator_compatible_browser browser id': 1,
 'accelerator_compatible_browser browser compatible_since_year': 1,
 'accelerator_compatible_browser web_client_accelerator compatible_since_year': 1,
 'browser web_client_accelerator compatible_since_year': 1,
 'accelerator_compatible_browser browser operating_system': 1,
 'accelerator_compatible_browser web_client_accelerator operating_system': 1,
 'browser web_client_accelerator operating_system': 1,
 'elimination wrestler name': 4,
 'elimination wrestler elimination_move': 2,
 'elimination wrestler team': 2,
 'elimination wrestler time': 4,
 'endowment school donator_name': 3,
 'endowment school school_name': 3,
 'budget school school_name': 3,
 'budget school budgeted': 2,
 'budget school invested': 1,
 'budget endowment school_name': 1,
 '( ) *': 9,
 'budget school mascot': 1,
 'budget school ihsaa_football_class': 1,
 'building institution name': 3,
 'building institution *': 2,
 'building institution height_feet': 1,
 'institution protein institution': 2,
 'institution protein *': 3,
 'institution protein protein_name': 1,
 'building protein *': 1,
 'cinema schedule name': 2,
 'cinema schedule show_times_per_day': 1,
 'film schedule title': 3,
 'film schedule price': 3,
 'cinema film name': 1,
 'cinema film title': 1,
 'cinema film date': 1,
 'cinema film price': 1,
 'cinema schedule title': 1,
 'cinema schedule date': 1,
 'cinema schedule price': 1,
 'film schedule name': 1,
 'film schedule date': 1,
 'film schedule directed_by': 1,
 'customers discount_coupons good_or_bad_customer': 1,
 'bookings customers customer_id': 1,
 'bookings customers first_name': 1,
 'bookings customers *': 1,
 'bookings payments booking_id': 1,
 'bookings payments amount_of_refund': 1,
 'products_booked products_for_hire product_description': 1,
 'bookings products_booked booking_start_date': 1,
 'bookings products_booked booking_end_date': 1,
 'bookings products_for_hire booking_start_date': 1,
 'bookings products_for_hire booking_end_date': 1,
 'products_booked products_for_hire booking_start_date': 1,
 'products_booked products_for_hire booking_end_date': 1,
 'products_for_hire view_product_availability product_name': 1,
 'customers discount_coupons coupon_amount': 2,
 'market phone name': 3,
 'market phone district': 2,
 'market phone_market name': 3,
 'market phone_market district': 2,
 'phone phone_market name': 5,
 'phone phone_market district': 2,
 'phone phone_market num_of_stock': 1,
 'company station_company company': 2,
 'company station_company *': 2,
 'company gas_station manager_name': 2,
 'company station_company manager_name': 2,
 'gas_station station_company manager_name': 2,
 'company gas_station location': 4,
 'company station_company location': 4,
 'gas_station station_company location': 4,
 'company gas_station representative_name': 2,
 'company station_company representative_name': 2,
 'gas_station station_company representative_name': 2,
 'member party member_name': 4,
 'member party party_name': 6,
 'member party *': 2,
 'party region party_name': 2,
 'party region region_name': 2,
 'party party_events party_name': 4,
 'party party_events *': 4,
 'member party_events member_name': 4,
 'party region *': 2,
 'party_events region *': 2,
 'aircraft pilot pilot_name': 2,
 'aircraft pilot model': 1,
 'aircraft pilot_record pilot_name': 2,
 'aircraft pilot_record model': 1,
 'pilot pilot_record pilot_name': 4,
 'pilot pilot_record model': 1,
 'aircraft pilot fleet_series': 2,
 'aircraft pilot_record fleet_series': 2,
 'pilot pilot_record fleet_series': 2,
 'pilot pilot_record *': 2,
 'employees roles role_description': 4,
 'employees roles role_code': 1,
 'employees roles *': 1,
 'employees roles roles.role_description': 1,
 'employees roles employees.employee_id': 1,
 'documents ref_document_status ref_document_status.document_status_description': 1,
 'documents ref_shipping_agents ref_shipping_agents.shipping_agent_name': 2,
 'documents ref_shipping_agents *': 1,
 'documents ref_shipping_agents documents.document_id': 1,
 'addresses documents_mailed addresses.address_details': 1,
 'documents ref_shipping_agents document_id': 2,
 'circulation_history employees employees.employee_name': 3,
 'circulation_history employees *': 1,
 'department dept_locations dname': 1,
 'events services event_details': 1,
 'events participants_in_events event_id': 1,
 'events participants_in_events event_details': 1,
 'participants participants_in_events participant_id': 1,
 'participants participants_in_events participant_type_code': 1,

In [3]:

if all(entity in join for entity in mapped_entities):
    print('True')

False

In [7]:
from nltk.corpus import wordnet
syns = wordnet.synsets("instructor")
print(syns)

[Synset('teacher.n.01')]

In [185]:
#TODO
#Merge with aggreagtion of select attributes???
#handle having aggregations
#handle order by ASC/DESC
#handle duplicate attributes in where clause
#attribute from same entity in select and where clause

##################################################################


#Remove After 'as'
#stop wored ''
#check prev
#From,Join ===> Entity Name
#On,Where ===> Attribute Name 
#or token == 'group' or token == 'limit' or token == 'offset' or token == 'having'
#Aggregation in select attributes

# entity => e ,attributes => a
# SELECT TO FROM ===> Attribute Name
# From TO WHERE ==> Entity Name (REMOVE JOIN,AS,After as|| ON attribte=> Split on '.')
# NESTED select do recursion with brackets(())
# SELECT after Intersect
# SELECT after Union
# SELECT after Except
# IN_NOT_IN
###############################
# WHERE Type of Condition
# Group By
# Order By
# Limit
# Offset
# Having

In [ ]:
#TODO
#tokenize dataset like spider 
#lemmatize
#remove '_'  ===> as general as possible
#embeddings
#distance between words